version: '3'
services:
  apache:
    build: .docker/apache
    container_name: makapi_apache
    ports:
      - ${DOCKER_APACHE_PORT}:80
    volumes:
      - .docker/config/vhosts:/etc/apache2/sites-enabled
      - .:/home/wwwroot/makapi
    depends_on:
      - php

  mysql:
    image: mysql:5.6
    container_name: makapi_mysql
    volumes:
      - .docker/data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_MYSQL_DBNAME}
      MYSQL_USER: ${DOCKER_MYSQL_USER}
      MYSQL_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
    ports:
      - ${DOCKER_MYSQL_PORT}:3306

  php:
    build: .docker/php
    container_name: makapi_php
    volumes:
      - .:/home/wwwroot/makapi
    environment:
      - maildev_host=makapi_maildev
    depends_on:
      - maildev
      - mysql

  maildev:
    image: djfarrelly/maildev
    container_name: makapi_maildev
    ports:
      - ${DOCKER_MAILDEV_PORT}:80