version: '3'
services:
  apache:
    build: .docker/apache
    container_name: sf4_apache
    ports:
      - ${DOCKER_APACHE_PORT}:80
    volumes:
      - .docker/config/vhosts:/etc/apache2/sites-enabled
      - .:/home/wwwroot/sf4
    depends_on:
      - php

  mysql:
    image: mysql:5.6
    container_name: sf4_mysql
    volumes:
      - .docker/data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_MYSQL_DBNAME}
      MYSQL_USER: ${DOCKER_MYSQL_USER}
      MYSQL_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
    ports:
      - ${DOCKER_MYSQL_PORT}:3306

  php:
    build: .docker/php
    container_name: sf4_php
    volumes:
      - .:/home/wwwroot/sf4
    environment:
      - maildev_host=sf4_maildev
    depends_on:
      - maildev
      - mysql

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    container_name: sf4_phpmyadmin
#    ports:
#      - 8080:80
#    links:
#      - mysql

  maildev:
    image: djfarrelly/maildev
    container_name: sf4_maildev
    ports:
      - ${DOCKER_MAILDEV_PORT}:80