rest_controllers:
    resource: ../../src/Controller/Rest
    type: 'annotation'
    prefix: '/api'

front_controllers:
    resource: ../../src/Controller/Front
    type: annotation
    prefix: '/'

generator_controller:
    resource: ../src/Controller/Generator
    type: annotation
    prefix: '/'

back_controllers:
    resource: ../../src/Controller/Back
    type: annotation
    prefix: '/admin'